name: Deploy to Pages branch

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare publish folder
        run: |
          rm -rf dist
          mkdir -p dist
          cp index.html dist/index.html
          cp -R assets dist/assets

      - name: Deploy to pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: pages
          folder: dist
          clean: true
          single-commit: true
